version: '3.7'

services:
    php-apache:
        build:
            context: .
        environment:
            - SYMFONY_PARAMS=${SYMFONY_PARAMS}
        volumes:
            - type: bind
              source: ./src
              target: /usr/src
        ports:
            - '8080:80'

    

volumes:
    dbdata:
    
